services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Avro\CsvBundle\Import\Importer:
        arguments:
            $batchSize: '%avro_csv.batch_size%'

    Avro\CsvBundle\Import\ImporterInterface: '@Avro\CsvBundle\Import\Importer'

    Avro\CsvBundle\Export\Doctrine\ORM\Exporter: ~

    Avro\CsvBundle\Export\ExporterInterface: '@Avro\CsvBundle\Export\Doctrine\ORM\Exporter'
