services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Avro\CsvBundle\Util\Reader: ~

    Avro\CsvBundle\Util\FieldRetriever: ~

    Avro\CsvBundle\Controller\ExportController:
        public: true

    Avro\CsvBundle\Controller\ImportController:
        public: true
