language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_install:
  - |
    # php.ini configuration
    INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    phpenv config-rm xdebug.ini || echo "xdebug not available"
    echo memory_limit = -1 >> $INI

install:
  - composer install --no-interaction --prefer-dist

notifications:
  email: joris.w.dewit@gmail.com
